default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: atom
  password: ecoolapi

development:
  <<: *default
  database: atom_development

test:
  <<: *default
  database: atom_test

production:
  <<: *default
  database: atom_production
