# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   username: atom
#   password: ecoolapi

development: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5
  username: root
  password: 1234
  host: 127.0.0.1

development:
  <<: *default
  database: atom_development

test:
  <<: *default
  database: atom_test

production:
  <<: *default
  database: atom_production
